CREATE TABLE direct_messages
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_user_id     BIGINT                                  NOT NULL,
    to_user_id       BIGINT                                  NOT NULL,
    from_user_server VARCHAR(255),
    to_user_server   VARCHAR(255),
    message          VARCHAR(5000),
    is_read          BOOLEAN,
    is_edited        BOOLEAN,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_direct_messages PRIMARY KEY (id)
);