CREATE TABLE channel_messages
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id              BIGINT                                  NOT NULL,
    channel_id           BIGINT                                  NOT NULL,
    space_id             BIGINT                                  NOT NULL,
    from_user_server     VARCHAR(255),
    message              VARCHAR(5000),
    is_edited            BOOLEAN,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    federated_message_id VARCHAR(255),
    CONSTRAINT pk_channel_messages PRIMARY KEY (id)
);

ALTER TABLE channel_messages
    ADD CONSTRAINT FK_CHANNEL_MESSAGES_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES channels (id);

ALTER TABLE channel_messages
    ADD CONSTRAINT FK_CHANNEL_MESSAGES_ON_SPACE FOREIGN KEY (space_id) REFERENCES spaces (id);

ALTER TABLE channel_messages
    ADD CONSTRAINT FK_CHANNEL_MESSAGES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);